package mcpclient

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// GenOptions configures the Go code generator.
type GenOptions struct {
	// PackageName is the Go package name of the generated file (required).
	PackageName string

	// FuncName is the name of the generated registration function.
	// Default: "RegisterMCPSession".
	FuncName string

	// Tag is an optional build tag placed at the top of the generated file.
	Tag string
}

// GenerateTools produces formatted Go source code that creates Starlark
// builtins for every MCP tool listed in tools.  The generated code is a
// complete .go file ready to write to disk and compile.
//
// The generated file exports a function (FuncName, default RegisterMCPSession)
// with the signature:
//
//	func RegisterMCPSession(session *mcp.ClientSession) starlark.StringDict
//
// Each tool becomes a starlark.Builtin that accepts keyword arguments,
// forwards them to the remote MCP server via session.CallTool, and returns
// the result as a starlark.Value.  Argument names and descriptions from the
// JSON schema properties are included as comments.
func GenerateTools(tools []*ToolInfo, opts GenOptions) ([]byte, error) {
	if opts.PackageName == "" {
		return nil, fmt.Errorf("mcpclient: GenOptions.PackageName is required")
	}
	if opts.FuncName == "" {
		opts.FuncName = "RegisterMCPSession"
	}

	// Build template data.
	data := &genData{
		PackageName: opts.PackageName,
		FuncName:    opts.FuncName,
		HasTools:    len(tools) > 0,
		Tools:       make([]genTool, len(tools)),
	}

	for i, t := range tools {
		gt := genTool{
			Name:            t.Name,
			Description:     t.Description,
			InputPropNames:  extractPropertyNames(t.InputSchema),
			OutputPropNames: extractPropertyNames(t.OutputSchema),
		}

		// Build a user-friendly description comment.
		var sb strings.Builder
		sb.WriteString(escapeComment(t.Name))
		if t.Description != "" {
			sb.WriteString(" - ")
			sb.WriteString(escapeComment(t.Description))
		}

		hasSchema := len(gt.InputPropNames) > 0 || len(gt.OutputPropNames) > 0
		if hasSchema {
			sb.WriteString("\n//")
		}
		if len(gt.InputPropNames) > 0 {
			sb.WriteString("\n// Inputs:")
			for _, p := range gt.InputPropNames {
				sb.WriteString("\n//   ")
				sb.WriteString(escapeComment(p))
			}
		}
		if len(gt.OutputPropNames) > 0 {
			sb.WriteString("\n// Outputs:")
			for _, p := range gt.OutputPropNames {
				sb.WriteString("\n//   ")
				sb.WriteString(escapeComment(p))
			}
		}
		gt.Doc = sb.String()

		data.Tools[i] = gt
	}

	// Execute the template.
	var buf bytes.Buffer
	if err := genTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("mcpclient: template execute: %w", err)
	}

	// gofmt the output.
	out, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source as a fallback so the user can inspect.
		return buf.Bytes(), fmt.Errorf("mcpclient: format source: %w", err)
	}
	return out, nil
}

// -- template data types -- //

type genData struct {
	PackageName string
	FuncName    string
	HasTools    bool
	Tools       []genTool
	Tag         string
}

type genTool struct {
	Name            string
	Description     string
	Doc             string // full comment block for the entry
	InputPropNames  []string
	OutputPropNames []string
}

// -- helpers -- //

func extractPropertyNames(schema map[string]any) []string {
	if schema == nil {
		return nil
	}
	props, _ := schema["properties"].(map[string]any)
	if props == nil {
		return nil
	}
	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	return names
}

func escapeComment(s string) string {
	// The template adds "// " prefix; just ensure no unprintable chars.
	return strings.ReplaceAll(s, "\n", " ")
}

// -- template -- //

var genTemplate = template.Must(template.New("gen").Funcs(template.FuncMap{
	"quote": func(s string) string { return fmt.Sprintf("%q", s) },
	"trim":  strings.TrimSpace,
}).Parse(`// Code generated by mcpclient. DO NOT EDIT.
// Source: github.com/mishudark/citron/mcpclient

{{- if .Tag }}
//go:build {{.Tag}}
{{- end }}

package {{.PackageName}}

import (
	"context"
	"fmt"

	"github.com/mishudark/citron/mcpclient"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"go.starlark.net/starlark"
)

// {{.FuncName}} creates Starlark builtins for every MCP tool advertised by the
// remote server. The returned starlark.StringDict can be merged into a citron
// execution context so that Starlark code can call the remote tools.
//
// Example:
//
//	dict := RegisterMCPSession(session)
//	starlark.ExecFile(thread, "agent.star", code, dict)
func {{.FuncName}}(session *mcp.ClientSession) starlark.StringDict {
	_ = session // ensure session is "used" even when tools is empty
	{{- if not .HasTools }}
	return starlark.StringDict{}
	{{- else }}
	return starlark.StringDict{
	{{- range .Tools }}
		// {{.Doc}}
		{{.Name | quote}}: starlark.NewBuiltin({{.Name | quote}}, func(thread *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
			params := make(map[string]any, len(kwargs))
			for _, kv := range kwargs {
				params[string(kv[0].(starlark.String))] = mcpclient.FromStarlark(kv[1])
			}
			result, err := session.CallTool(context.Background(), &mcp.CallToolParams{
				Name:      {{.Name | quote}},
				Arguments: params,
			})
			if err != nil {
				return nil, fmt.Errorf("mcp tool %s: %w", {{.Name | quote}}, err)
			}
			return mcpclient.MCPResultToStarlark(result)
		}),
	{{- end }}
	}
	{{- end }}
}
`))
