package citron

import (
	"bytes"
	"context"
	_ "embed"
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/mishudark/citron/analysis"
	"github.com/mishudark/citron/caps"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/trace"
	"go.starlark.net/starlark"
	"go.starlark.net/syntax"
)

//go:embed HARNESS_GUIDE.md
var HarnessGuide string

// threadContextKey carries the execution context (including the timeout
// deadline) through the Starlark thread so capability calls made from
// generated MCP builtins honor cancellation.
const threadContextKey = "citron.ctx"

type Options struct {
	// WorkingDir is the virtual root path for filesystem operations.
	// All fs.access() calls are resolved relative to this root.
	// Defaults to "/work" if empty.
	WorkingDir string

	// SeedDir is an optional real directory whose files are copied
	// into the virtual filesystem before execution begins.
	// When empty, the virtual filesystem starts clean.
	SeedDir string

	CommandAllowlist   []string
	NetworkAllowlist   []string
	ClassifiedPatterns []string
	SecureOutputPath   string
	TimeoutMs          int64

	// TracerProvider sets the OpenTelemetry tracer provider for
	// capability spans. When nil, the global OTel tracer is used.
	TracerProvider trace.TracerProvider

	// MeterProvider sets the OpenTelemetry meter provider for
	// capability metrics. When nil, the global OTel meter is used.
	MeterProvider metric.MeterProvider

	// DoNotTrack disables all OpenTelemetry tracing and metrics
	// collection for this execution or session. When true, no
	// telemetry data is exported regardless of TracerProvider
	// or MeterProvider settings.
	DoNotTrack bool

	// MetricsOutputPath is an optional file path for writing
	// OpenTelemetry metrics after execution completes. When set,
	// metrics are exported in JSON format to this file. Taking
	// precedence over MeterProvider when both are set.
	MetricsOutputPath string

	// Extras is an optional set of additional Starlark globals injected
	// into the execution context alongside fs, net, proc, and io.
	// This is used to supply remote MCP tool bindings generated by
	// mcpclient.GenerateAll.
	Extras starlark.StringDict
}

type Result struct {
	Output   string
	Duration int64
}

func Analyze(code string) error {
	issues, err := analysis.Analyze("agent.star", []byte(code))
	if err != nil {
		return err
	}
	if len(issues) > 0 {
		return errors.Join(toErrorList(issues)...)
	}
	return nil
}

// validateExtras rejects injected globals (e.g. remote MCP tool bindings)
// whose names collide with Starlark builtins the analyzer treats as pure.
// Such a global shadows the builtin, so a callback like
// `secret.map(str)` would call the remote tool with the unwrapped
// classified value, silently defeating purity verification.
func validateExtras(extras starlark.StringDict) error {
	for name := range extras {
		if analysis.IsPureBuiltin(name) {
			return fmt.Errorf("citron: extras global %q shadows the pure builtin %q; rename the remote tool", name, name)
		}
	}
	return nil
}

func toErrorList(issues []analysis.Issue) []error {
	errs := make([]error, len(issues))
	for i, iss := range issues {
		errs[i] = iss
	}
	return errs
}

// seedVirtualFS copies all regular files from a real directory into a VirtualFileSystem.
func seedVirtualFS(vfs *caps.VirtualFileSystem, root, seedDir string) error {
	return filepath.WalkDir(seedDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(seedDir, path)
		if err != nil {
			return err
		}
		vfs.Set(filepath.Join(root, filepath.ToSlash(rel)), string(content))
		return nil
	})
}

func vfsWorkingDir(opts Options) string {
	if opts.WorkingDir != "" {
		return opts.WorkingDir
	}
	return "/work"
}

// applyTelemetry configures the caps package telemetry providers based on
// the provided options. When DoNotTrack is true, noop providers are used
// regardless of any TracerProvider or MeterProvider settings.
// Returns a function that flushes any pending metric data (no-op if no SDK
// provider was created), and an error when metric export setup fails so the
// caller can surface it instead of silently dropping metrics.
func applyTelemetry(opts Options) (func(), error) {
	if opts.DoNotTrack {
		caps.SetNoopTelemetry()
		return func() {}, nil
	}

	if opts.TracerProvider != nil {
		caps.SetTracerProvider(opts.TracerProvider)
	}
	if opts.MeterProvider != nil {
		caps.SetMeterProvider(opts.MeterProvider)
	}

	// When a metrics output path is set, create an SDK meter provider
	// that writes metrics to the specified file.
	if opts.MetricsOutputPath != "" {
		f, err := os.Create(opts.MetricsOutputPath)
		if err != nil {
			return func() {}, fmt.Errorf("citron: opening metrics output %q: %w", opts.MetricsOutputPath, err)
		}
		exporter, err := stdoutmetric.New(stdoutmetric.WithWriter(f))
		if err != nil {
			_ = f.Close()
			return func() {}, fmt.Errorf("citron: creating metrics exporter: %w", err)
		}
		reader := sdkmetric.NewPeriodicReader(exporter)
		provider := sdkmetric.NewMeterProvider(
			sdkmetric.WithReader(reader),
		)
		caps.SetMeterProvider(provider)
		return func() {
			_ = provider.ForceFlush(context.Background())
			_ = provider.Shutdown(context.Background())
			_ = f.Close()
		}, nil
	}

	return func() {}, nil
}

func SafeExecute(code string, opts Options) (*Result, error) {
	flushMetrics, err := applyTelemetry(opts)
	if err != nil {
		return nil, err
	}
	defer flushMetrics()

	_, span := caps.StartSpan(context.Background(), "citron.SafeExecute",
		attribute.String("working_dir", vfsWorkingDir(opts)),
		attribute.Bool("has_seed", opts.SeedDir != ""),
	)

	if err := Analyze(code); err != nil {
		caps.EndSpan(span, err)
		caps.RecordOperationWithKind(context.Background(), "safe_execute", "analysis", err)
		return nil, err
	}

	if err := validateExtras(opts.Extras); err != nil {
		caps.EndSpan(span, err)
		caps.RecordOperationWithKind(context.Background(), "safe_execute", "setup", err)
		return nil, err
	}

	start := time.Now()

	var secureOut *os.File
	if opts.SecureOutputPath != "" {
		f, err := os.OpenFile(opts.SecureOutputPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
		if err != nil {
			caps.EndSpan(span, err)
			caps.RecordOperationWithKind(context.Background(), "safe_execute", "setup", err)
			return nil, err
		}
		defer func() { _ = f.Close() }()
		secureOut = f
	}

	var agentOut bytes.Buffer
	ioCap := caps.NewIOCapability(secureOut, &agentOut)

	dict := starlark.StringDict{
		"io": &starlarkIO{io: ioCap},
	}
	// Extras can supply additional globals, but built-in capabilities
	// always take precedence.
	maps.Copy(dict, opts.Extras)
	dict["io"] = &starlarkIO{io: ioCap}

	vfs := caps.NewVirtualFileSystem()
	wd := vfsWorkingDir(opts)
	if opts.SeedDir != "" {
		if err := seedVirtualFS(vfs, wd, opts.SeedDir); err != nil {
			caps.EndSpan(span, err)
			caps.RecordOperationWithKind(context.Background(), "safe_execute", "setup", err)
			return nil, fmt.Errorf("seed: %w", err)
		}
	}

	var execErr error
	fsCfg := &caps.FileSystemConfig{ClassifiedPatterns: opts.ClassifiedPatterns}

	ctx := context.Background()
	var cancel context.CancelFunc
	if opts.TimeoutMs > 0 {
		ctx, cancel = context.WithTimeout(ctx, time.Duration(opts.TimeoutMs)*time.Millisecond)
		defer cancel()
	}

	thread := &starlark.Thread{Name: "agent"}
	thread.Print = func(_ *starlark.Thread, msg string) { ioCap.Println(msg) }

	done := make(chan error, 1)
	go func() {
		_, execErr = caps.RequestVirtualFileSystem(wd, vfs, fsCfg, func(fs caps.FileSystem) (any, error) {
			dict["fs"] = &starlarkFileSystem{fs: fs}
			_, errNet := caps.RequestNetwork(opts.NetworkAllowlist, func(net caps.Network) (any, error) {
				dict["net"] = &starlarkNetwork{n: net}
				_, errProc := caps.RequestExecPermission(opts.CommandAllowlist, func(proc caps.ProcessPermission) (any, error) {
					dict["proc"] = &starlarkProc{p: proc}
					thread.SetLocal(threadContextKey, ctx)
					_, errStar := starlark.ExecFileOptions(&syntax.FileOptions{}, thread, "agent.star", code, dict)
					return nil, errStar
				})
				return nil, errProc
			})
			return nil, errNet
		})
		done <- execErr
	}()

	select {
	case execErr = <-done:
	case <-ctx.Done():
		thread.Cancel(fmt.Sprintf("execution timed out after %dms", opts.TimeoutMs))
		<-done
		duration := time.Since(start)
		caps.EndSpan(span, fmt.Errorf("execution timed out after %dms", opts.TimeoutMs))
		caps.RecordOperationWithKind(context.Background(), "safe_execute", "timeout", fmt.Errorf("execution timed out after %dms", opts.TimeoutMs))
		caps.RecordOperationDuration(context.Background(), "safe_execute", duration, fmt.Errorf("execution timed out after %dms", opts.TimeoutMs))
		return nil, fmt.Errorf("execution timed out after %dms", opts.TimeoutMs)
	}

	duration := time.Since(start)

	if execErr != nil {
		caps.EndSpan(span, execErr)
		caps.RecordOperationWithKind(context.Background(), "safe_execute", "runtime", execErr)
		caps.RecordOperationDuration(context.Background(), "safe_execute", duration, execErr)
		return nil, formatExecError(execErr)
	}

	caps.EndSpan(span, nil)
	caps.RecordOperationWithKind(context.Background(), "safe_execute", "", nil)
	caps.RecordOperationDuration(context.Background(), "safe_execute", duration, nil)
	return &Result{
		Output:   agentOut.String(),
		Duration: time.Since(start).Milliseconds(),
	}, nil
}

type Session struct {
	opts    Options
	vfs     *caps.VirtualFileSystem
	globals starlark.StringDict
	mu      sync.Mutex
}

func NewSession(opts Options) *Session {
	// Apply non-file telemetry config at session creation time.
	// File-based metric export (MetricsOutputPath) is handled per Execute call.
	if opts.DoNotTrack {
		caps.SetNoopTelemetry()
	} else {
		if opts.TracerProvider != nil {
			caps.SetTracerProvider(opts.TracerProvider)
		}
		if opts.MeterProvider != nil {
			caps.SetMeterProvider(opts.MeterProvider)
		}
	}
	vfs := caps.NewVirtualFileSystem()
	wd := vfsWorkingDir(opts)
	if opts.SeedDir != "" {
		_ = seedVirtualFS(vfs, wd, opts.SeedDir)
	}
	return &Session{
		opts:    opts,
		vfs:     vfs,
		globals: make(starlark.StringDict),
	}
}

func (s *Session) Execute(code string) (*Result, error) {
	flushMetrics, err := applyTelemetry(s.opts)
	if err != nil {
		return nil, err
	}
	defer flushMetrics()

	_, span := caps.StartSpan(context.Background(), "citron.Session.Execute",
		attribute.String("working_dir", vfsWorkingDir(s.opts)),
		attribute.Bool("has_seed", s.opts.SeedDir != ""),
	)

	if err := Analyze(code); err != nil {
		caps.EndSpan(span, err)
		caps.RecordOperationWithKind(context.Background(), "session_execute", "analysis", err)
		return nil, err
	}

	if err := validateExtras(s.opts.Extras); err != nil {
		caps.EndSpan(span, err)
		caps.RecordOperationWithKind(context.Background(), "session_execute", "setup", err)
		return nil, err
	}

	start := time.Now()

	var secureOut *os.File
	if s.opts.SecureOutputPath != "" {
		f, err := os.OpenFile(s.opts.SecureOutputPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
		if err != nil {
			caps.EndSpan(span, err)
			caps.RecordOperationWithKind(context.Background(), "session_execute", "setup", err)
			return nil, err
		}
		defer func() { _ = f.Close() }()
		secureOut = f
	}

	var agentOut bytes.Buffer
	ioCap := caps.NewIOCapability(secureOut, &agentOut)

	// Each execution gets its own copy of the session globals so concurrent
	// Execute calls never share the underlying map. Capability bindings are
	// injected per run and never merged back, so stale handles cannot persist.
	s.mu.Lock()
	globals := make(starlark.StringDict, len(s.globals)+4)
	maps.Copy(globals, s.globals)
	s.mu.Unlock()
	maps.Copy(globals, s.opts.Extras)
	globals["io"] = &starlarkIO{io: ioCap} // builtins take precedence

	var execErr error

	ctx := context.Background()
	var cancel context.CancelFunc
	if s.opts.TimeoutMs > 0 {
		ctx, cancel = context.WithTimeout(ctx, time.Duration(s.opts.TimeoutMs)*time.Millisecond)
		defer cancel()
	}

	fsCfg := &caps.FileSystemConfig{ClassifiedPatterns: s.opts.ClassifiedPatterns}
	wd := vfsWorkingDir(s.opts)

	thread := &starlark.Thread{Name: "agent"}
	thread.Print = func(_ *starlark.Thread, msg string) { ioCap.Println(msg) }

	done := make(chan error, 1)
	go func() {
		_, execErr = caps.RequestVirtualFileSystem(wd, s.vfs, fsCfg, func(fs caps.FileSystem) (any, error) {
			globals["fs"] = &starlarkFileSystem{fs: fs}
			_, errNet := caps.RequestNetwork(s.opts.NetworkAllowlist, func(net caps.Network) (any, error) {
				globals["net"] = &starlarkNetwork{n: net}
				_, errProc := caps.RequestExecPermission(s.opts.CommandAllowlist, func(proc caps.ProcessPermission) (any, error) {
					globals["proc"] = &starlarkProc{p: proc}

					thread.SetLocal(threadContextKey, ctx)
					resultDict, errStar := starlark.ExecFileOptions(&syntax.FileOptions{}, thread, "agent.star", code, globals)
					if errStar == nil {
						for name, value := range resultDict {
							switch name {
							case "io", "fs", "net", "proc":
								continue
							}
							globals[name] = value
						}
					}
					return nil, errStar
				})
				return nil, errProc
			})
			return nil, errNet
		})
		done <- execErr
	}()

	select {
	case execErr = <-done:
	case <-ctx.Done():
		thread.Cancel(fmt.Sprintf("execution timed out after %dms", s.opts.TimeoutMs))
		<-done
		duration := time.Since(start)
		caps.EndSpan(span, fmt.Errorf("execution timed out after %dms", s.opts.TimeoutMs))
		caps.RecordOperationWithKind(context.Background(), "session_execute", "timeout", fmt.Errorf("execution timed out after %dms", s.opts.TimeoutMs))
		caps.RecordOperationDuration(context.Background(), "session_execute", duration, fmt.Errorf("execution timed out after %dms", s.opts.TimeoutMs))
		return nil, fmt.Errorf("execution timed out after %dms", s.opts.TimeoutMs)
	}

	duration := time.Since(start)

	// Merge script-defined globals back into the session state (excluding
	// per-run capability bindings) after the exec goroutine has exited.
	s.mu.Lock()
	for name, value := range globals {
		switch name {
		case "io", "fs", "net", "proc":
			continue
		}
		s.globals[name] = value
	}
	s.mu.Unlock()

	if execErr != nil {
		caps.EndSpan(span, execErr)
		caps.RecordOperationWithKind(context.Background(), "session_execute", "runtime", execErr)
		caps.RecordOperationDuration(context.Background(), "session_execute", duration, execErr)
		return nil, formatExecError(execErr)
	}

	caps.EndSpan(span, nil)
	caps.RecordOperationWithKind(context.Background(), "session_execute", "", nil)
	caps.RecordOperationDuration(context.Background(), "session_execute", duration, nil)
	return &Result{
		Output:   agentOut.String(),
		Duration: time.Since(start).Milliseconds(),
	}, nil
}

func (s *Session) Close() {}

// formatExecError enriches a Starlark evaluation error with the full call
// stack traceback.
func formatExecError(err error) error {
	var evalErr *starlark.EvalError
	if errors.As(err, &evalErr) {
		return fmt.Errorf("agent.star: %s\n%s", evalErr.Msg, evalErr.Backtrace())
	}
	return err
}
